export const invalidDirectory = 'Ação inválida, forneça um arquivo ao invés de um diretório.'
export const fileNotFound = 'Arquivo não encontrado.'
export const invalidExtension = 'Forneça um arquivo de extensão .md.'
export const inexistingLinks = 'Arquivo não contém links.'
export const noFile = 'Nenhum arquivo fornecido, nenhum arquivo analisado.'
